
database :
  jdbc-driver :
    subprotocol : "postgresql"
    subname : "//localhost:5432/erindb"
  meta-data :
    schema : "erin"
    tables :
       people :  "people"
       characters : "characters"
       photos : "photos"
       networks : "networks"
       shows : "shows"
       episodes : "shows"
       media_types: "media_types"
       character_xref : "character_xref"
       person_xref : "person_xref"
       rel_types : "rel_types"
       credits : "credits"
       person_roles : "person_roles"
       credits_summary : "credits_summary"
       social_links : "social_links"
       social_link_types : "social_link_types"
       shows_and_people : "shows_and_people"
    primary-keys :
       media_types : "media_type"
       social_link_types: "link_type"

http :
   port : 8080
