<div id="shows-relationships">
<ul>
   <li><a href="/v1/erin-form.html?entity=episodes&key=series_id&value={id}&parent_entity=shows">Episodes</a><br/></li>
    <li><a href="/v1/erin-form.html?entity=credits&key=table_id&value={id}&parent_entity=shows&summary_view=credits_summary">Credits</a><br/></li>
    <li><a href="/v1/erin-form.html?entity=social_links&key=table_id&value={id}">Social Links</a></li>

</ul>
</div>